##### Fichier de déploiement cPanel (Test)######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fmcsproc/futech.fmcspro.ca/FutechMSAddIns/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp Administration_Tab.xml $DEPLOYPATH
    - /bin/cp commands_administration.html $DEPLOYPATH
    - /bin/cp futFormatPaFourListe.js $DEPLOYPATH